# Generated by Django 4.2.4 on 2025-01-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=650)),
                ('price', models.FloatField()),
                ('images', models.ImageField(upload_to='photos/products')),
                ('imgfile', models.TextField(blank=True, max_length=300)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField(blank=True, default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('peso', models.FloatField(default=0)),
                ('costo_prod', models.FloatField(blank=True, default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=10)),
                ('precio_TN', models.FloatField(blank=True, default=0)),
                ('precio_ML', models.FloatField(blank=True, default=0)),
                ('sku_meli', models.CharField(blank=True, max_length=420)),
                ('url_meli', models.CharField(blank=True, max_length=650)),
                ('es_kit', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size'), ('letra', 'letra')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], default='porcentaje', max_length=20)),
                ('valor_descuento', models.FloatField()),
                ('cantidad_minima', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('monto_desde', models.FloatField()),
                ('monto_hasta', models.FloatField()),
                ('acumulable', models.BooleanField(default=False)),
                ('categoria', models.ManyToManyField(blank=True, to='category.category')),
                ('productos', models.ManyToManyField(blank=True, to='store.product')),
                ('subcategoria', models.ManyToManyField(blank=True, to='category.subcategory')),
            ],
            options={
                'verbose_name': 'Regla de Descuento',
                'verbose_name_plural': 'Reglas de Descuento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductKitEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_unidades', models.FloatField()),
                ('cant_variedades', models.FloatField()),
                ('productokit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'producto kit encabezado',
                'verbose_name_plural': 'producto kit encabezado',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'productgallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costo',
            },
        ),
        migrations.CreateModel(
            name='ProductKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productohijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('productokit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productkitenc')),
            ],
            options={
                'verbose_name': 'producto_kit',
                'verbose_name_plural': 'producto_kit',
                'unique_together': {('productokit', 'productohijo')},
            },
        ),
    ]
