# Generated by Django 4.2.4 on 2023-09-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_create_date_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('letra', 'letra')], max_length=100),
        ),
    ]
