# Generated by Django 4.2.4 on 2023-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
