# Generated by Django 4.2.4 on 2024-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgfile',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
