# Generated by Django 4.2.4 on 2024-08-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
