# Generated by Django 4.2.4 on 2024-08-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_costo_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='costo',
            field=models.FloatField(),
        ),
    ]
