# Generated by Django 4.2.4 on 2024-09-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_costo_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costo_prod',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
