# Generated by Django 4.2.4 on 2024-09-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_costo_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ubicacion',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
