# Generated by Django 4.2.4 on 2024-09-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='precio_ML',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_TN',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
