# Generated by Django 4.2.4 on 2024-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_precio_ml_product_precio_tn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
