# Generated by Django 4.2.4 on 2024-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_meli',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='url_meli',
            field=models.CharField(blank=True, max_length=650),
        ),
    ]
