# Generated by Django 4.2.4 on 2024-10-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_sku_meli_product_url_meli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costo',
            options={'verbose_name': 'Costo', 'verbose_name_plural': 'Costo'},
        ),
        migrations.AddField(
            model_name='product',
            name='es_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('productohijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_hijo', to='store.product')),
                ('productokit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits_padre', to='store.product')),
            ],
            options={
                'verbose_name': 'producto_kit',
                'verbose_name_plural': 'producto_kit',
            },
        ),
    ]
