# Generated by Django 4.2.4 on 2024-11-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_costo_options_product_es_kit_productkitenc_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productkit',
            unique_together={('productokit', 'productohijo')},
        ),
    ]
