# Generated by Django 4.2.4 on 2024-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productkit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku_meli',
            field=models.CharField(blank=True, max_length=420),
        ),
    ]
