# Generated by Django 4.2.4 on 2024-12-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_sku_meli'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
