# Generated by Django 4.2.4 on 2024-12-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_category_options'),
        ('store', '0019_product_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la regla de descuento', max_length=200, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], default='porcentaje', help_text='Tipo de descuento (porcentaje o monto fijo)', max_length=20)),
                ('valor_descuento', models.FloatField(help_text='Valor del descuento (porcentaje o monto fijo)')),
                ('cantidad_minima', models.IntegerField(blank=True, default=0, help_text='Cantidad mínima para aplicar el descuento', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio del descuento', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de fin del descuento', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el descuento está activo o no')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
                ('productos', models.ManyToManyField(blank=True, null=True, to='store.product')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory')),
            ],
            options={
                'verbose_name': 'Regla de Descuento',
                'verbose_name_plural': 'Reglas de Descuento',
                'ordering': ['nombre'],
            },
        ),
    ]
