# Generated by Django 4.2.4 on 2024-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_regladescuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladescuento',
            name='productos',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
