# Generated by Django 4.2.4 on 2024-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_regladescuento_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='regladescuento',
            name='acumulable',
            field=models.BooleanField(default=True, help_text='Promo Acumulable'),
        ),
        migrations.AddField(
            model_name='regladescuento',
            name='monto_desde',
            field=models.FloatField(default=1, help_text='Rango de Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regladescuento',
            name='monto_hasta',
            field=models.FloatField(default=1, help_text='Rango de Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Rango Fijo')], default='porcentaje', help_text='Tipo de descuento (porcentaje o monto fijo)', max_length=20),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='valor_descuento',
            field=models.FloatField(help_text='Valor del descuento (porcentaje'),
        ),
    ]
