# Generated by Django 4.2.4 on 2024-12-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_regladescuento_acumulable_regladescuento_monto_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladescuento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='acumulable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='cantidad_minima',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='monto_desde',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='monto_hasta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Rango Fijo')], default='porcentaje', max_length=20),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='valor_descuento',
            field=models.FloatField(),
        ),
    ]
