# Generated by Django 4.2.4 on 2024-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_category_options'),
        ('store', '0023_alter_regladescuento_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regladescuento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='regladescuento',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='tipo_descuento',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], default='porcentaje', max_length=20),
        ),
        migrations.AddField(
            model_name='regladescuento',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='category.category'),
        ),
        migrations.AddField(
            model_name='regladescuento',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, null=True, to='category.subcategory'),
        ),
    ]
