# Generated by Django 4.2.4 on 2024-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_category_options'),
        ('store', '0024_remove_regladescuento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regladescuento',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
        migrations.AlterField(
            model_name='regladescuento',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, to='category.subcategory'),
        ),
    ]
