branch-defaults:
  main:
    environment: django-ecomm-env
environment-defaults:
  django-ecomm-env:
    branch: null
    repository: null
global:
  application_name: django-ecomm-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
