# Generated by Django 4.2.4 on 2024-12-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_regladescuento_categoria_and_more'),
        ('carts', '0003_alter_cartitemkit_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='desc_unit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='id_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.regladescuento'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='precio_con_desc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='precio_real',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sub_total_linea',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
