# Generated by Django 4.2.4 on 2024-12-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_regladescuento_categoria_and_more'),
        ('carts', '0004_cartitem_desc_unit_cartitem_id_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='id_descuento',
        ),
        migrations.CreateModel(
            name='CartItemDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('descuento_unit', models.FloatField()),
                ('descuento_total', models.FloatField()),
                ('porcentaje_descuento', models.IntegerField()),
                ('cartitemid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cartitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('regladescuento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.regladescuento')),
            ],
        ),
    ]
