# Generated by Django 4.2.4 on 2025-01-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_type', models.CharField(max_length=50)),
                ('identification_number', models.CharField(max_length=50)),
                ('taxpayer_type_id', models.CharField(max_length=10)),
                ('taxpayer_type_description', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country_id', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'BillingInfo',
                'verbose_name_plural': 'BillingInfo',
            },
        ),
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('permiso', models.CharField(max_length=100)),
                ('rootpath', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPermition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_ver', models.BooleanField(default=False)),
                ('modo_editar', models.BooleanField(default=False)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDirecciones',
            fields=[
                ('dir_id', models.AutoField(primary_key=True, serialize=False, verbose_name='dir_id')),
                ('dir_nombre', models.CharField(max_length=50)),
                ('dir_cp', models.CharField(max_length=10)),
                ('dir_calle', models.CharField(max_length=100)),
                ('dir_nro', models.CharField(max_length=25)),
                ('dir_piso', models.CharField(blank=True, max_length=10)),
                ('dir_depto', models.CharField(blank=True, max_length=10)),
                ('dir_localidad', models.CharField(blank=True, max_length=50)),
                ('dir_provincia', models.CharField(blank=True, max_length=50)),
                ('dir_area_tel', models.CharField(blank=True, max_length=5)),
                ('dir_telefono', models.CharField(max_length=25)),
                ('dir_obs', models.CharField(blank=True, max_length=250)),
                ('dir_tipocorreo', models.BigIntegerField(default=0)),
                ('dir_tipoenvio', models.BigIntegerField(default=0)),
                ('dir_correo', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
