# Generated by Django 4.2.4 on 2023-10-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permition',
            name='codigo',
            field=models.CharField(max_length=25),
        ),
    ]
