# Generated by Django 4.2.4 on 2023-09-07 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('permiso', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPermition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
