# Generated by Django 4.2.4 on 2024-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permition_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_area_tel',
            field=models.CharField(default=11, max_length=5),
            preserve_default=False,
        ),
    ]
