# Generated by Django 4.2.4 on 2024-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdirecciones_dir_area_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_correo',
            field=models.BigIntegerField(default=False),
        ),
    ]
