# Generated by Django 4.2.4 on 2023-09-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permition_accountpermition'),
    ]

    operations = [
        migrations.AddField(
            model_name='permition',
            name='rootpath',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permition',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
