# Generated by Django 4.2.4 on 2023-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permition_rootpath_alter_permition_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpermition',
            name='ver',
        ),
    ]
