# Generated by Django 4.2.4 on 2024-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountdirecciones_dir_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdirecciones',
            old_name='dir_correo',
            new_name='dir_tipocorreo',
        ),
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_tipoenvio',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
