# Generated by Django 4.2.4 on 2023-09-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_accountpermition_ver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpermition',
            old_name='editar',
            new_name='modo_editar',
        ),
    ]
