# Generated by Django 4.2.4 on 2024-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_dir_correo_accountdirecciones_dir_tipocorreo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_tipoenvio',
            field=models.BigIntegerField(default=0),
        ),
    ]
