# Generated by Django 4.2.4 on 2024-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountdirecciones_dir_tipoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_correo',
            field=models.BigIntegerField(default=0),
        ),
    ]
