# Generated by Django 4.2.4 on 2023-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_editar_accountpermition_modo_editar'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpermition',
            name='modo_ver',
            field=models.BooleanField(default=False),
        ),
    ]
