# Generated by Django 4.2.4 on 2023-09-13 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountpermition_modo_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDirecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_nombre', models.CharField(max_length=50)),
                ('dir_cp', models.CharField(max_length=10)),
                ('dir_calle', models.CharField(max_length=100)),
                ('dir_nro', models.CharField(max_length=25)),
                ('dir_localidad', models.CharField(max_length=50)),
                ('dir_provincia', models.CharField(max_length=50)),
                ('dir_telefono', models.CharField(max_length=25)),
                ('dir_obs', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
