# Generated by Django 4.2.4 on 2024-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountdirecciones_dir_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_depto',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_piso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_area_tel',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_localidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_obs',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
