# Generated by Django 4.2.4 on 2023-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountdirecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdirecciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
