# Generated by Django 4.2.4 on 2024-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountdirecciones_dir_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_depto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='accountdirecciones',
            name='dir_piso',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
