# Generated by Django 4.2.4 on 2023-09-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accountdirecciones_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdirecciones',
            name='id',
        ),
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='dir_id'),
            preserve_default=False,
        ),
    ]
