# Generated by Django 4.2.4 on 2024-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accountdirecciones_dir_depto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_type', models.CharField(max_length=50)),
                ('identification_number', models.CharField(max_length=50)),
                ('taxpayer_type_id', models.CharField(max_length=10)),
                ('taxpayer_type_description', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country_id', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'BillingInfo',
                'verbose_name_plural': 'BillingInfo',
            },
        ),
    ]
