# Generated by Django 4.2.4 on 2023-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_accountdirecciones_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdirecciones',
            name='dir_correo',
            field=models.BooleanField(default=False),
        ),
    ]
