# Generated by Django 4.2.4 on 2023-10-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category_image',
        ),
    ]
