# Generated by Django 4.2.4 on 2023-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
