# Generated by Django 4.2.4 on 2023-11-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_subcategory_sub_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=50),
        ),
    ]
