# Generated by Django 4.2.4 on 2024-03-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_orden_subcategory_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['orden'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
