# Generated by Django 4.2.4 on 2024-08-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_subcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_picking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_picking', models.IntegerField(default=0)),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Orden picking',
                'verbose_name_plural': 'Orden picking',
                'ordering': ['orden_picking'],
            },
        ),
    ]
