# Generated by Django 4.2.4 on 2024-08-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_orden_picking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orden_picking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='orden_picking',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Orden_picking',
        ),
    ]
