# Generated by Django 4.2.4 on 2024-10-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_category_orden_picking_subcategory_orden_picking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
