# Generated by Django 4.2.4 on 2024-10-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
