# Generated by Django 4.2.4 on 2024-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meli_params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('grant_type', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('redirect_uri', models.CharField(blank=True, max_length=100)),
                ('client_secret', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('token_type', models.CharField(blank=True, max_length=100)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meli_Param',
                'verbose_name_plural': 'Meli_Params',
                'ordering': ['client_id'],
            },
        ),
    ]
