# Generated by Django 4.2.4 on 2024-04-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meli_params',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='meli_params',
            name='grant_type',
        ),
        migrations.RemoveField(
            model_name='meli_params',
            name='redirect_uri',
        ),
    ]
