# Generated by Django 4.2.4 on 2023-10-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='', max_length=50, verbose_name='Descripcion')),
                ('limite', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, verbose_name='Codigo')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Simbolo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(default='', max_length=100, null=True)),
                ('monto', models.FloatField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('idtransferencia', models.BigIntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentas')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('movimiento', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(default='', max_length=100, null=True)),
                ('monto_origen', models.FloatField(default=0)),
                ('conversion', models.FloatField(default=0)),
                ('monto_destino', models.FloatField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='contabilidad.cuentas')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='contabilidad.cuentas')),
                ('idmov_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='contabilidad.movimientos')),
                ('idmov_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='contabilidad.movimientos')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.operaciones')),
            ],
            options={
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientos',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.operaciones'),
        ),
        migrations.AddField(
            model_name='movimientos',
            name='ordernumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.monedas'),
        ),
    ]
