# Generated by Django 4.2.4 on 2023-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentas',
            name='limite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
