# Generated by Django 4.2.4 on 2023-09-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cuentas_is_available_cuentas_limite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentas',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(default='', max_length=100, null=True)),
                ('monto', models.FloatField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('idtransferencia', models.BigIntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentas')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.monedas')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.operaciones')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
