# Generated by Django 4.2.4 on 2023-09-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('contabilidad', '0003_alter_cuentas_unique_together_alter_cuentas_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='idorderpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
        ),
    ]
