# Generated by Django 4.2.4 on 2024-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cuentas_alias_cuentas_cbu_cuentas_cuil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('mes', models.BigIntegerField(default=0)),
                ('anio', models.BigIntegerField(default=0)),
                ('ing_saldo_pesos', models.FloatField(default=0)),
                ('ing_saldo_dolar', models.FloatField(default=0)),
                ('egr_saldo_pesos', models.FloatField(default=0)),
                ('egr_saldo_dolar', models.FloatField(default=0)),
                ('tot_saldo_pesos', models.FloatField(default=0)),
                ('tot_saldo_dolar', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cierre Mesual',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
