# Generated by Django 4.2.4 on 2023-09-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
        ('contabilidad', '0004_movimientos_idorderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='idorderpayment',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='ordernumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
