# Generated by Django 4.2.4 on 2024-08-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_cierremes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cierremes',
            unique_together={('mes', 'anio')},
        ),
    ]
