# Generated by Django 4.2.4 on 2023-10-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_remove_movimientos_idorderpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(default='', max_length=100, null=True)),
                ('monto', models.FloatField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_destino', to='contabilidad.cuentas')),
                ('cuenta_oigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_origen', to='contabilidad.cuentas')),
                ('idmov_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_destino', to='contabilidad.movimientos')),
                ('idmov_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mov_origen', to='contabilidad.movimientos')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_destino', to='contabilidad.monedas')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_origen', to='contabilidad.monedas')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.operaciones')),
            ],
            options={
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
