# Generated by Django 4.2.4 on 2024-08-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_alter_cierremes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='idcierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cierremes'),
        ),
    ]
