# Generated by Django 4.2.4 on 2024-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_movimientos_idcierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='idcierre',
            field=models.BigIntegerField(default=0),
        ),
    ]
