# Generated by Django 4.2.4 on 2023-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_transferencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencias',
            old_name='monto',
            new_name='conversion',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='transferencias',
            name='moneda_destino',
        ),
        migrations.RemoveField(
            model_name='transferencias',
            name='moneda_origen',
        ),
        migrations.AddField(
            model_name='transferencias',
            name='monto_destino',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transferencias',
            name='monto_origen',
            field=models.FloatField(default=0),
        ),
    ]
