# Generated by Django 4.2.4 on 2023-10-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_rename_monto_transferencias_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencias',
            old_name='cuenta_oigen',
            new_name='cuenta_origen',
        ),
    ]
