# Generated by Django 4.2.4 on 2023-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_rename_cuenta_oigen_transferencias_cuenta_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='limite',
            field=models.IntegerField(default=0),
        ),
    ]
