# Generated by Django 4.2.4 on 2024-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_configuracionparametros_alter_movimientos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionparametros',
            options={'ordering': ['id'], 'verbose_name_plural': 'Configuracion Parametros'},
        ),
        migrations.AlterField(
            model_name='configuracionparametros',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
