# Generated by Django 4.2.4 on 2023-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTempOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_total', models.FloatField()),
                ('dir_telefono', models.CharField(blank=True, max_length=25)),
                ('dir_calle', models.CharField(blank=True, max_length=100)),
                ('dir_nro', models.CharField(blank=True, max_length=25)),
                ('dir_localidad', models.CharField(blank=True, max_length=50)),
                ('dir_provincia', models.CharField(blank=True, max_length=50)),
                ('dir_cp', models.CharField(blank=True, max_length=10)),
                ('dir_obs', models.CharField(blank=True, max_length=255)),
                ('dir_correo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportTempOrdersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportTempProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('variation_category', models.CharField(blank=True, max_length=25)),
                ('variation_value', models.CharField(blank=True, max_length=25)),
                ('price', models.IntegerField()),
                ('images', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=25)),
            ],
        ),
    ]
