# Generated by Django 4.2.4 on 2025-01-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('codigo', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('compra', models.FloatField()),
                ('venta', models.FloatField()),
                ('promedio', models.FloatField()),
                ('fechaActualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ImportDolar',
                'verbose_name_plural': 'ImportDolar',
            },
        ),
        migrations.CreateModel(
            name='ImportTempOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order_total', models.FloatField()),
                ('dir_telefono', models.CharField(blank=True, max_length=25)),
                ('dir_calle', models.CharField(blank=True, max_length=100)),
                ('dir_nro', models.CharField(blank=True, max_length=25)),
                ('dir_localidad', models.CharField(blank=True, max_length=50)),
                ('dir_provincia', models.CharField(blank=True, max_length=50)),
                ('dir_cp', models.CharField(blank=True, max_length=10)),
                ('dir_obs', models.CharField(blank=True, max_length=255)),
                ('dir_tipocorreo', models.BigIntegerField(default=0)),
                ('usuario', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ImportTempOrder',
                'verbose_name_plural': 'ImportTempOrders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTempProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=650)),
                ('variation_category', models.CharField(blank=True, max_length=25)),
                ('variation_value', models.CharField(blank=True, max_length=25)),
                ('price', models.IntegerField()),
                ('images', models.CharField(blank=True, max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=25)),
                ('peso', models.FloatField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=10)),
                ('costo_prod', models.FloatField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'ImportTempProduct',
                'verbose_name_plural': 'ImportTempProduct',
                'ordering': ['-product_name'],
                'unique_together': {('slug', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ImportTempOrdersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('usuario', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=False)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.importtemporders')),
            ],
            options={
                'verbose_name': 'ImportTempOrdersDetail',
                'verbose_name_plural': 'ImportTempOrdersDetails',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
