# Generated by Django 4.2.4 on 2023-09-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importtemporders',
            options={'verbose_name': 'ImportTempOrders', 'verbose_name_plural': 'ImportTempOrders'},
        ),
        migrations.AlterModelOptions(
            name='importtempordersdetail',
            options={'verbose_name': 'ImportTempOrdersDetail', 'verbose_name_plural': 'ImportTempOrdersDetail'},
        ),
    ]
