# Generated by Django 4.2.4 on 2023-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtempproduct',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
