# Generated by Django 4.2.4 on 2023-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_importtempproduct_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempproduct',
            name='description',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
