# Generated by Django 4.2.4 on 2023-09-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_importtemporders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importtemporders',
            options={'ordering': ['-created_at'], 'verbose_name': 'ImportTempOrders', 'verbose_name_plural': 'ImportTempOrders'},
        ),
        migrations.AlterModelOptions(
            name='importtempproduct',
            options={'ordering': ['-product_name'], 'verbose_name': 'ImportTempProduct', 'verbose_name_plural': 'ImportTempProduct'},
        ),
    ]
