# Generated by Django 4.2.4 on 2023-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_importtemporders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtemporders',
            name='usuario',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
