# Generated by Django 4.2.4 on 2023-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_importtempproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempproduct',
            name='usuario',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
