# Generated by Django 4.2.4 on 2023-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_importtemporders_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtempordersdetail',
            name='usuario',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
