# Generated by Django 4.2.4 on 2023-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_importtempproduct_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempproduct',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='importtempproduct',
            unique_together={('slug', 'usuario')},
        ),
    ]
