# Generated by Django 4.2.4 on 2023-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_importtempordersdetail_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importtemporders',
            options={'ordering': ['-created_at'], 'verbose_name': 'ImportTempOrder', 'verbose_name_plural': 'ImportTempOrders'},
        ),
        migrations.AlterModelOptions(
            name='importtempordersdetail',
            options={'verbose_name': 'ImportTempOrdersDetail', 'verbose_name_plural': 'ImportTempOrdersDetails'},
        ),
        migrations.AddField(
            model_name='importtempordersdetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
