# Generated by Django 4.2.4 on 2023-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_importtempproduct_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempproduct',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='importtempproduct',
            name='usuario',
            field=models.CharField(max_length=25),
        ),
    ]
