# Generated by Django 4.2.4 on 2023-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_importtemporders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempordersdetail',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
