# Generated by Django 4.2.4 on 2023-11-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_importtempproduct_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtemporders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
