# Generated by Django 4.2.4 on 2023-11-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_importtemporders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempordersdetail',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.importtemporders'),
        ),
    ]
