# Generated by Django 4.2.4 on 2023-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_importtempordersdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtemporders',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
