# Generated by Django 4.2.4 on 2023-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_importtemporders_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtemporders',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='importtemporders',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
