# Generated by Django 4.2.4 on 2024-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_importtempordersdetail_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtempproduct',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
