# Generated by Django 4.2.4 on 2024-08-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_importtempproduct_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=50)),
                ('compra', models.FloatField()),
                ('venta', models.FloatField()),
                ('promedio', models.FloatField()),
                ('fechaActualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ImportDolar',
                'verbose_name_plural': 'ImportDolar',
            },
        ),
    ]
