# Generated by Django 4.2.4 on 2024-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_importdolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdolar',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
