# Generated by Django 4.2.4 on 2024-08-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_importdolar_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtemporders',
            name='dir_correo',
        ),
        migrations.AddField(
            model_name='importtemporders',
            name='dir_tipocorreo',
            field=models.BigIntegerField(default=0),
        ),
    ]
