# Generated by Django 4.2.4 on 2024-10-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_importtempproduct_costo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtempproduct',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
