# Generated by Django 4.2.4 on 2024-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
