# Generated by Django 4.2.4 on 2024-08-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_alter_movimientos_idcierre'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuentas')),
            ],
            options={
                'verbose_name': 'CompraDolar',
                'verbose_name_plural': 'CompraDolares',
            },
        ),
        migrations.DeleteModel(
            name='CompratDolar',
        ),
    ]
