# Generated by Django 4.2.4 on 2024-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_proveedores_proveedorarticulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='instragram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='web',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
