# Generated by Django 4.2.4 on 2024-09-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_proveedores_telefono_proveedores_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='codigo',
        ),
    ]
