# Generated by Django 4.2.4 on 2024-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_proveedores_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorarticulos',
            name='cantidad_unidad_medida',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='proveedorarticulos',
            name='marca',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedorarticulos',
            name='precio_por_unidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proveedorarticulos',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
