# Generated by Django 4.2.4 on 2024-09-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_proveedorarticulos_cantidad_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedorarticulos',
            unique_together={('proveedor', 'codigo_prod_prov')},
        ),
    ]
