# Generated by Django 4.2.4 on 2024-09-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_proveedorarticulos_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UnidadMedida',
                'verbose_name_plural': 'UnidadMedida',
            },
        ),
        migrations.AlterField(
            model_name='proveedorarticulos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.marcas'),
        ),
        migrations.AlterField(
            model_name='proveedorarticulos',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.unidadmedida'),
            preserve_default=False,
        ),
    ]
