# Generated by Django 4.2.4 on 2024-09-09 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_marcas_unidadmedida_alter_proveedorarticulos_marca_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedorarticulos',
            unique_together={('proveedor', 'codigo_prod_prov', 'unidad_medida')},
        ),
    ]
