# Generated by Django 4.2.4 on 2024-09-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_proveedorarticulos_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorarticulos',
            name='link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
