# Generated by Django 4.2.4 on 2024-09-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_proveedorarticulos_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorarticulos',
            name='peso_por_unidad',
            field=models.FloatField(default=0),
        ),
    ]
