# Generated by Django 4.2.4 on 2024-09-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_costo_costo'),
        ('compras', '0011_proveedorarticulos_peso_por_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorarticulos',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
