# Generated by Django 4.2.4 on 2024-09-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_costo_costo'),
        ('compras', '0012_proveedorarticulos_id_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorarticulos',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
