# Generated by Django 4.2.4 on 2024-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
