# Generated by Django 4.2.4 on 2024-09-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_comprasenc_id_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorarticulos',
            options={'ordering': ['nombre_articulo'], 'verbose_name': 'ProveedorArticulos', 'verbose_name_plural': 'ProveedorArticulos'},
        ),
    ]
