# Generated by Django 4.2.4 on 2025-01-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('fecha', models.DateField(blank=True)),
                ('dir_nombre', models.CharField(blank=True, max_length=50)),
                ('dir_telefono', models.CharField(max_length=25)),
                ('dir_calle', models.CharField(blank=True, max_length=100)),
                ('dir_nro', models.CharField(blank=True, max_length=25)),
                ('dir_piso', models.CharField(blank=True, max_length=10)),
                ('dir_depto', models.CharField(blank=True, max_length=10)),
                ('dir_localidad', models.CharField(blank=True, max_length=50)),
                ('dir_provincia', models.CharField(blank=True, max_length=50)),
                ('dir_cp', models.CharField(blank=True, max_length=10)),
                ('dir_obs', models.CharField(blank=True, max_length=255)),
                ('dir_tipocorreo', models.BigIntegerField(default=0)),
                ('dir_tipoenvio', models.BigIntegerField(blank=True, default=0)),
                ('dir_correo', models.BigIntegerField(blank=True, default=0)),
                ('order_note', models.CharField(blank=True, max_length=250)),
                ('order_total', models.FloatField()),
                ('envio', models.FloatField(blank=True, default=0)),
                ('order_total_comisiones', models.FloatField(blank=True, default=0)),
                ('order_total_descuentos', models.FloatField(blank=True, default=0)),
                ('order_total_impuestos', models.FloatField(blank=True, default=0)),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cobrado', 'Cobrado'), ('Entregado', 'Entregado')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_peso', models.FloatField(default=0)),
                ('cuenta', models.BigIntegerField(default=0)),
                ('fecha_tracking', models.DateTimeField(blank=True, null=True)),
                ('nro_tracking', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.FloatField()),
                ('descuento_unitario', models.FloatField(blank=True, default=0)),
                ('precio_unitario_cobrado', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrigenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('origen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Origen Venta',
                'verbose_name_plural': 'Origen Ventas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='orders.orderproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_components', to='store.product')),
            ],
            options={
                'verbose_name': 'Order Product Kit',
                'verbose_name_plural': 'Order Products Kits',
                'ordering': ['-order_product'],
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
        migrations.AddField(
            model_name='order',
            name='origen_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.origenventa'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
