# Generated by Django 4.2.4 on 2023-12-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_peso',
            field=models.FloatField(default=0),
        ),
    ]
