# Generated by Django 4.2.4 on 2023-09-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='dir_localidad',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='dir_provincia',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='dir_calle',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dir_cp',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dir_nro',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dir_obs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='dir_telefono',
            field=models.CharField(default='0000', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
