# Generated by Django 4.2.4 on 2023-09-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address_line_1_order_dir_localidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='envio',
        ),
    ]
