# Generated by Django 4.2.4 on 2023-12-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cuenta',
            field=models.BigIntegerField(default=0),
        ),
    ]
