# Generated by Django 4.2.4 on 2023-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_tax_order_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dir_correo',
            field=models.BooleanField(default=False),
        ),
    ]
