# Generated by Django 4.2.4 on 2024-03-01 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha_tracking',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='nro_tracking',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
