# Generated by Django 4.2.4 on 2023-09-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cobrado', 'Cobrado'), ('Entregado', 'Entregado')], default='New', max_length=10),
        ),
    ]
