# Generated by Django 4.2.4 on 2024-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha_tracking',
            field=models.DateTimeField(blank=True),
        ),
    ]
