# Generated by Django 4.2.4 on 2023-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
