# Generated by Django 4.2.4 on 2023-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
