# Generated by Django 4.2.4 on 2024-03-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_fecha_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fecha_tracking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
