# Generated by Django 4.2.4 on 2024-08-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_fecha_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='costo',
            field=models.FloatField(default=0),
        ),
    ]
