# Generated by Django 4.2.4 on 2024-08-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dir_correo',
        ),
        migrations.AddField(
            model_name='order',
            name='dir_tipocorreo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='dir_tipoenvio',
            field=models.BigIntegerField(default=0),
        ),
    ]
