# Generated by Django 4.2.4 on 2024-08-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_dir_correo_order_dir_tipocorreo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dir_calle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='dir_cp',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='dir_localidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='dir_nro',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='dir_provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='dir_tipoenvio',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
