# Generated by Django 4.2.4 on 2024-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_dir_calle_alter_order_dir_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dir_nombre',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
