# Generated by Django 4.2.4 on 2024-09-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_dir_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_number'], 'verbose_name': 'Order', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
