# Generated by Django 4.2.4 on 2024-09-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_number'], 'verbose_name': 'Order', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
