# Generated by Django 4.2.4 on 2024-11-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_dir_correo_alter_order_dir_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('origen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Origen Venta',
                'verbose_name_plural': 'Origen Ventas',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='dir_depto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='dir_piso',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_comisiones',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_descuentos',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total_impuestos',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='origen_venta',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='descuento_unitario',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='precio_unitario_cobrado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='envio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
