# Generated by Django 4.2.4 on 2024-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_dir_correo_alter_order_dir_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dir_depto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='dir_piso',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
