# Generated by Django 4.2.4 on 2024-11-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_origenventa_order_dir_depto_order_dir_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='origen_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.origenventa'),
        ),
    ]
