# Generated by Django 4.2.4 on 2024-11-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productkit_unique_together'),
        ('orders', '0017_alter_order_origen_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='orders.orderproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_components', to='store.product')),
            ],
            options={
                'verbose_name': 'Order Product Kit',
                'verbose_name_plural': 'Order Products Kits',
                'ordering': ['-order_product'],
            },
        ),
    ]
